/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as HebergementsRouteImport } from './routes/hebergements'
import { Route as InformationsRouteImport } from './routes/informations'
import { Route as LieuRouteImport } from './routes/lieu'
import { Route as ProgrammeRouteImport } from './routes/programme'
import { Route as RegionRouteImport } from './routes/region'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const HebergementsRoute = HebergementsRouteImport.update({
  id: '/hebergements',
  path: '/hebergements',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationsRoute = InformationsRouteImport.update({
  id: '/informations',
  path: '/informations',
  getParentRoute: () => rootRouteImport,
} as any)
const LieuRoute = LieuRouteImport.update({
  id: '/lieu',
  path: '/lieu',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeRoute = ProgrammeRouteImport.update({
  id: '/programme',
  path: '/programme',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionRoute = RegionRouteImport.update({
  id: '/region',
  path: '/region',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/hebergements': typeof HebergementsRoute
  '/informations': typeof InformationsRoute
  '/lieu': typeof LieuRoute
  '/programme': typeof ProgrammeRoute
  '/region': typeof RegionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/hebergements': typeof HebergementsRoute
  '/informations': typeof InformationsRoute
  '/lieu': typeof LieuRoute
  '/programme': typeof ProgrammeRoute
  '/region': typeof RegionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/hebergements': typeof HebergementsRoute
  '/informations': typeof InformationsRoute
  '/lieu': typeof LieuRoute
  '/programme': typeof ProgrammeRoute
  '/region': typeof RegionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostic'
    | '/faq'
    | '/galerie'
    | '/hebergements'
    | '/informations'
    | '/lieu'
    | '/programme'
    | '/region'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostic'
    | '/faq'
    | '/galerie'
    | '/hebergements'
    | '/informations'
    | '/lieu'
    | '/programme'
    | '/region'
  id:
    | '__root__'
    | '/'
    | '/diagnostic'
    | '/faq'
    | '/galerie'
    | '/hebergements'
    | '/informations'
    | '/lieu'
    | '/programme'
    | '/region'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticRoute: typeof DiagnosticRoute
  FaqRoute: typeof FaqRoute
  GalerieRoute: typeof GalerieRoute
  HebergementsRoute: typeof HebergementsRoute
  InformationsRoute: typeof InformationsRoute
  LieuRoute: typeof LieuRoute
  ProgrammeRoute: typeof ProgrammeRoute
  RegionRoute: typeof RegionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hebergements': {
      id: '/hebergements'
      path: '/hebergements'
      fullPath: '/hebergements'
      preLoaderRoute: typeof HebergementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informations': {
      id: '/informations'
      path: '/informations'
      fullPath: '/informations'
      preLoaderRoute: typeof InformationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lieu': {
      id: '/lieu'
      path: '/lieu'
      fullPath: '/lieu'
      preLoaderRoute: typeof LieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme': {
      id: '/programme'
      path: '/programme'
      fullPath: '/programme'
      preLoaderRoute: typeof ProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region': {
      id: '/region'
      path: '/region'
      fullPath: '/region'
      preLoaderRoute: typeof RegionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticRoute: DiagnosticRoute,
  FaqRoute: FaqRoute,
  GalerieRoute: GalerieRoute,
  HebergementsRoute: HebergementsRoute,
  InformationsRoute: InformationsRoute,
  LieuRoute: LieuRoute,
  ProgrammeRoute: ProgrammeRoute,
  RegionRoute: RegionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
